services:
  - type: web
    name: iia-institute-erp
    env: node
    region: singapore
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: iia_erp_super_secret_jwt_key_2026
