import mongoose, { Schema } from 'mongoose';
const StudentSchema = new Schema({
    studentId: { type: String, required: true, unique: true },
    leadId: { type: Schema.Types.ObjectId, ref: 'Lead' },
    name: { type: String, required: true, trim: true },
    dob: { type: Date },
    phone: { type: String, required: true, trim: true },
    whatsapp: { type: String, required: true, trim: true },
    email: { type: String, required: true, lowercase: true, trim: true },
    address: { type: String, default: '' },
    fatherName: { type: String, default: '' },
    motherName: { type: String, default: '' },
    guardianName: { type: String, default: '' },
    parentPhone: { type: String, default: '' },
    parentWhatsapp: { type: String, default: '' },
    parentEmail: { type: String, default: '' },
    parentOccupation: { type: String, default: '' },
    emergencyContact: { type: String, default: '' },
    verificationStatus: { type: String, enum: ['Pending', 'Verified', 'Rejected'], default: 'Verified' },
    courseId: { type: Schema.Types.ObjectId, ref: 'Course' },
    courseName: { type: String, required: true },
    level: { type: String, required: true },
    packageType: { type: String, default: 'Quarterly' },
    batchId: { type: Schema.Types.ObjectId, ref: 'Batch' },
    batchCode: { type: String },
    teacherName: { type: String, default: 'Prof. Amit Kulkarni' },
    joiningDate: { type: Date, default: Date.now },
    admissionDate: { type: Date, default: Date.now },
    documents: [
        {
            type: { type: String, required: true },
            url: { type: String, required: true },
            status: { type: String, enum: ['Pending', 'Submitted', 'Verified'], default: 'Submitted' },
        },
    ],
    timeline: [
        {
            title: { type: String, required: true },
            detail: { type: String },
            by: { type: String },
            at: { type: Date, default: Date.now },
        },
    ],
    referralSource: { type: String },
    isActive: { type: Boolean, default: true },
    photoUrl: { type: String },
}, { timestamps: true });
export default mongoose.model('Student', StudentSchema);
